version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true

