require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'

Rails:
  Enabled: true
  RunRailsCops: true

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 70
  Exclude:
    - 'Rakefile'
    - 'rakelib/**/*.rake'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 20

