Rails:
  Enabled: true
  Excludes:
    - 'db/**'
  RunRailsCops: true

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'rakelib/**/*.rake'
    - 'spec/**/*.rb'

MethodLength:
  Max: 20

BlockLength:
  Max: 70

require:
  - rubocop-rails
  - rubocop-rspec
